# Generated by Django 5.1.5 on 2025-01-29 18:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Denumire')),
                ('lipids_per_100_gr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Lipids / 100gr')),
                ('fatty_acids_per_100_gr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Fatty acids / 100gr')),
                ('carbohydrates_per_100_gr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Carbohydrates / 100gr')),
                ('sugars_per_100_gr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Sugars / 100gr')),
                ('fiber_per_100_gr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Fiber / 100gr')),
                ('proteins_per_100_gr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Proteins / 100gr')),
                ('salt_per_100_gr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Salt / 100gr')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Denumire')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('carbohydrates', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fatty_acids', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('proteins', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('lipids', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('salt', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('calories', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
            options={
                'verbose_name': 'Produs',
                'verbose_name_plural': 'Produse',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Grams')),
                ('carbohydrates', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fatty_acids', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('proteins', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('lipids', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('salt', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('calories', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='rcpapp.ingredient', verbose_name='Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='rcpapp.recipe')),
            ],
            options={
                'verbose_name': 'Recipe ingredient',
                'verbose_name_plural': 'Recipe ingredients',
                'ordering': ['-id'],
            },
        ),
    ]
