# Generated by Django 5.1.5 on 2025-01-29 19:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcpapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductIngredient',
            new_name='RecipeIngredient',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates_per_100_gr',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Carbohydrates / 100gr'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fatty_acids_per_100_gr',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Fatty acids / 100gr'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fiber_per_100_gr',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Fiber / 100gr'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='lipids_per_100_gr',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Lipids / 100gr'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins_per_100_gr',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Proteins / 100gr'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='salt_per_100_gr',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Salt / 100gr'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugars_per_100_gr',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Sugars / 100gr'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
